### ISSUE TITLE
Uncaught TypeError: window.XDomainRequest is not a function

### ISSUE THREAD

**Issue by constantm** [mapbox/corslite#13]
I'm trying to use Mapbox with Ember.js, but I'm getting an error related to `window.XDomainRequest` on both Chrome and Firefox. Issue happens at https://github.com/mapbox/corslite/blob/master/corslite.js#L22

It looks like that bit should only be executed on IE, since `XDomainRequest` only exists in IE. However, it checks this with `!('withCredentials' in x)`, which returns true on Chrome and Firefox (which I assume it shouldn't)

I'd love to help fix this bug, but I'm afraid that I don't know enough about how CORS works.

**Comment by tmcw** [comment]
First thing would be to try this without Ember, and see if it works then. Ember could be overriding basic browser functionality - it would be kind of unexpected, but it's possible. Or another module could be. Given that this module works in isolation and not in your app, the task is to figure out where the incompatibility lies, by removing and then re-adding parts.

**Comment by constantm** [comment]
Okay I'll see if I can figure it out. Aaargh!

**Comment by constantm** [comment]
Okay, found the issue. The Ember addon, Ember-cli-mirage, uses a library called Pretender.js to capture XML requests. The fake `XMLHttpRequest` doesn't include the `withCredentials` property, which causes browser detection to break.
